// <auto-generated />
using System;
using BookMovie.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookMovie.Migrations
{
    [DbContext(typeof(EFDdataContext))]
    partial class EFDdataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BookMovie.Models.DatVe", b =>
                {
                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("sove")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenrap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sdt");

                    b.ToTable("DatVes");
                });

            modelBuilder.Entity("BookMovie.Models.LichChieu", b =>
                {
                    b.Property<string>("idLC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("giochieu")
                        .HasColumnType("datetime2");

                    

                    b.Property<string>("tenphim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenrap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idLC");

                    b.ToTable("LichChieus");
                });

            modelBuilder.Entity("BookMovie.Models.Phim", b =>
                {
                    b.Property<string>("tenphim")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("thoiluong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tenphim");

                    b.ToTable("Phims");
                });

            modelBuilder.Entity("BookMovie.Models.Rap", b =>
                {
                    b.Property<string>("tenrap")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("chotrong")
                        .HasColumnType("int");

                    b.HasKey("tenrap");

                    b.ToTable("Raps");
                });
#pragma warning restore 612, 618
        }
    }
}
